In [12]:
import numpy as np
import pandas as pd

In [1]:
# Simple function
def add(x, y):
    return x + y

print(add(3, 4))  # Output: 7


7


In [ ]:
add = lambda x, y: x + y
print(add(3, 4))  # Output: 7


In [4]:
def subract_1(a,b):
    return a-b

In [5]:
subract_1(9,8)

1

In [3]:
subract=lambda a,b:a-b
subract(9,8) #9-8

1

In [6]:
#Assignment multiplication and Division

In [7]:
# Simple function
def square(x):
    return x ** 2

print(square(5))  # Output: 25


25


In [8]:
square(2)

4

In [9]:
square = lambda x: x ** 2
print(square(5))  # Output: 25


25


In [17]:
list1=[2000, 30000, 40000,60000,'Apple']
list1

[2000, 30000, 40000, 60000, 'Apple']

In [19]:
np_array=np.array([1,2,3,4,5,])
np_array

array([1, 2, 3, 4, 5])

In [23]:
import timeit

python_list = [i for i in range(10**2)]
numpy_array = np.array(python_list)

python_list_time = timeit.timeit(lambda: sum(python_list), number=1000) #summing the same list
numpy_array_time = timeit.timeit(lambda: np.sum(numpy_array), number=1000)#summming the same array
print("Python List Time:", python_list_time, "seconds")
print("NumPy Array Time:", numpy_array_time, "seconds")

# Convert to minutes
python_list_time_minutes = python_list_time / 60
numpy_array_time_minutes = numpy_array_time / 60

print("Python List Time (minutes):", python_list_time_minutes)
print("NumPy Array Time (minutes):", numpy_array_time_minutes)

Python List Time: 0.0014586001634597778 seconds
NumPy Array Time: 0.009681600145995617 seconds
Python List Time (minutes): 2.431000272432963e-05
NumPy Array Time (minutes): 0.00016136000243326029


The performance difference between Python lists and NumPy arrays becomes more pronounced as the size of the data increases. NumPy is optimized for array operations, making it particularly efficient for large-scale numerical computations.

In [25]:
vector = np.array([1, 2, 3])
print(vector.ndim)  # Output: 1

1


In [26]:
vector

array([1, 2, 3])

In [27]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim)  # Output: 2

2


In [28]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:

cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube.ndim)  # Output: 3


3


In [30]:
cube

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:

hypercube = np.random.random((2, 3, 4, 5))
print(hypercube.ndim)  # Output: 4


4


In [34]:
hypercube

array([[[[8.65340057e-01, 1.58545918e-01, 5.75382744e-01,
          9.74713279e-01, 6.87636362e-01],
         [1.33798085e-01, 6.65919712e-01, 6.76594723e-01,
          9.58129156e-01, 8.42883954e-01],
         [1.21116719e-01, 4.40584519e-01, 4.95146212e-01,
          3.69525745e-01, 8.10629784e-01],
         [8.96907560e-01, 7.54824958e-01, 6.95711003e-01,
          8.76341006e-01, 6.11671403e-01]],

        [[2.93032381e-01, 7.47637995e-02, 2.36110142e-01,
          2.21660087e-01, 6.29684304e-01],
         [6.96971816e-01, 7.06578745e-01, 2.34525128e-01,
          5.31925572e-01, 4.63432806e-01],
         [1.29947466e-01, 7.01870748e-01, 3.03109618e-01,
          1.72053159e-03, 9.35497119e-01],
         [9.61066791e-01, 7.17196007e-01, 6.70850735e-01,
          9.85415416e-01, 3.52305892e-01]],

        [[9.03240926e-01, 7.91409075e-04, 1.11871694e-01,
          3.91756739e-01, 5.92125865e-02],
         [5.60325737e-01, 1.97926496e-01, 1.56687753e-01,
          8.80979448e-01, 5.8

In [35]:
#Broadcasting
data = np.array([1, 2,4,10])
data * 2

array([ 2,  4,  8, 20])

In [39]:
array_1 = np.array(range(1, 5)) #numpy_array.reshape(rows, columns)
array_1

array([1, 2, 3, 4])

In [40]:
matrix_2x2= array_1.reshape(2, 2)

print("2x2 Matrix:")
print(matrix_2x2)

2x2 Matrix:
[[1 2]
 [3 4]]


In [41]:
array2=np.array(range(1,11))
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
matrix_5x2=array2.reshape(5,2)


matrix_5x2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
array3=np.array(range(1,4))
array3

array([1, 2, 3])

In [45]:
matrix_3x1=array3.reshape(3,1)


matrix_3x1

array([[1],
       [2],
       [3]])

In [48]:
matrix_5x2.max()

10

In [49]:
matrix_5x2.min()


1

In [50]:
matrix_5x2.sum()

55

In [52]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

<img src="1.PNG" alt="Alt text" width="400"/>

In [55]:
data[0, 1]

2

<img src="2.PNG" alt="Alt text" width="400"/>


In [58]:
data[0:2]


array([[1, 2],
       [3, 4]])

<img src="3.PNG" alt="Alt text" width="400"/>


In [59]:
data2 = np.array([[1, 2], [5, 3], [4, 6]])
data2

array([[1, 2],
       [5, 3],
       [4, 6]])

In [60]:
data2.max()


6

In [61]:
data2.max(axis=0)

array([5, 6])

<img src="4.PNG" alt="Alt text" width="400"/>


In [62]:
data2.max(axis=1)

array([2, 5, 6])

<img src="5.PNG" alt="Alt text" width="400"/>


In [65]:
data3 = np.array([[1, 2,9], [5,10, 3], [6, 2,1]])
data3

array([[ 1,  2,  9],
       [ 5, 10,  3],
       [ 6,  2,  1]])

In [66]:
data3.max(axis=0)

array([ 6, 10,  9])

In [67]:
data3.max(axis=1)

array([ 9, 10,  6])

In [69]:
data4 = np.array([[1, 2,9,10,11,15], [15,10, 3,6,0,1], [6, 25,0,1,10,4]])
data4

array([[ 1,  2,  9, 10, 11, 15],
       [15, 10,  3,  6,  0,  1],
       [ 6, 25,  0,  1, 10,  4]])

In [70]:
data4.max(axis=0)

array([15, 25,  9, 10, 11, 15])

In [71]:
data4.max(axis=1)

array([15, 15, 25])

In [72]:
data_3 = np.array([[1, 2], [3, 4]])
data_3

array([[1, 2],
       [3, 4]])

In [74]:

ones = np.array([[1, 1], [1, 1]])
ones

array([[1, 1],
       [1, 1]])

In [77]:
data_3 + ones

array([[2, 3],
       [4, 5]])

<img src="6.PNG" alt="Alt text" width="400"/>


In [78]:
data_4 = np.array([[1, 2], [3, 4], [5, 6]])
data_4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
ones_row = np.array([[1, 1]])
ones_row

array([[1, 1]])

In [81]:
data_4 + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

<img src="7.PNG" alt="Alt text" width="400"/>


In [ ]:
# <img src="6.PNG" alt="Alt text" width="400"/>
# <img src="6.PNG" alt="Alt text" width="400"/>


In [ ]:
np.ones(3)


In [ ]:
np.zeros(3)


In [ ]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
#This will print a random float between 0.0 (inclusive) and 1.0 (exclusive).


rng.random(3) 

<img src="8.PNG" alt="Alt text" width="400"/>


In [ ]:
np.ones((3, 2))


In [ ]:
np.ones((3, 2))


In [ ]:
rng.random((3, 2))

<img src="9.PNG" alt="Alt text" width="400"/>


In [ ]:
rng.integers(5, size=(2, 4)) #rng.integers(low, high, size=None, dtype=int)


In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

In [ ]:
arr.transpose()

In [ ]:
arr.T

In [ ]:
#You can use flatten to flatten your array into a 1D array.

x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

In [ ]:
x.flatten()

In [ ]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])

In [ ]:
dataframe = pd.DataFrame(a)
dataframe

In [ ]:
row_1 = dataframe.loc[0]  # Access the entire row with label 1
row_1

In [ ]:
element_0_1 = dataframe.loc[0, 1]  # Access element at row 0, column '1'
element_0_1

In [ ]:
df = pd.read_csv('countries_of_the_world.csv')
df.head()

In [ ]:
df.tail()

In [ ]:
element_0_1 = df.loc[1]  # Access element at row 0, column '1'
element_0_1

In [ ]:
df2=pd.read_csv('world_population.csv')
df2

In [ ]:
df2[df2['Rank'] <= 10]


In [ ]:
specific_countries = ['Bangladesh','Brazil']

df2[df2['Country'].isin(specific_countries)]


In [ ]:
df2[df2['Country'].str.contains('United')]


In [ ]:
numpy_array_method = df2.head().to_numpy()
numpy_array_method

In [ ]:
df2.columns

In [ ]:
sorted_data = df2.sort_values(by='2022 Population', ascending=False)
sorted_data

In [ ]:
row1 = df2.iloc[0]  # Selects the first row
row1

In [ ]:
row1_5 = df2.iloc[1:5]  # Selects rows 2 to 4 (exclusive)
row1_5

In [ ]:
column3 = df2.iloc[:, 2]  # Selects the third column
column3

In [ ]:
import matplotlib.pyplot as plt

countries = df2.iloc[:, 2]#DataFrame.iloc[row_indices, column_indices]

population = df2.iloc[:, 5]

plt.figure(figsize=(10, 6))
plt.bar(countries, population, color='skyblue')
plt.xlabel('Country')
plt.ylabel('2022 Population')
plt.title('Population by Country')
plt.xticks(rotation=45, ha='right')
plt.show()


In [ ]:
continent_population = df2.groupby('Continent')['2022 Population'].sum()
print("Continent-wise Population:\n", continent_population)


In [ ]:
df2['Percentage of World Population'] = (df2['2022 Population'] / df2['World Population Percentage']) * 100


In [ ]:
plt.figure(figsize=(10, 6))
continent_population.plot(kind='bar', color='skyblue')
plt.title('Continent-wise Total Population in 2022')
plt.xlabel('Continent')
plt.ylabel('Total Population')
plt.show()


In [ ]:
import matplotlib.pyplot as plt

# Assuming 'Continent' is a column in your DataFrame
continent_population = df2.groupby('Continent')['2022 Population'].sum()

plt.figure(figsize=(8, 8))
plt.pie(continent_population, labels=continent_population.index, autopct='%1.1f%%', startangle=140, colors=['gold', 'lightcoral', 'lightgreen', 'lightskyblue', 'lightpink'])
plt.title('Continent-wise Population Distribution in 2022')
plt.show()


In [ ]:
top_n = 5  # Change this to the desired number
top_countries = df2.nlargest(top_n, '2022 Population')[['Country', '2022 Population']]
print(f'Top {top_n} Populated Countries in 2022:\n', top_countries)


In [ ]:
smallest_countries = df2.nsmallest(5, '2022 Population')[['Country', '2022 Population']]
print("Smallest Countries According to Population in 2022:\n", )
smallest_countries


In [ ]:
top_growth_rate_n = 5  # Change this to the desired number
top_growth_rate_countries = df2.nlargest(top_growth_rate_n, 'Growth Rate')[['Country', 'Growth Rate']]
print(f'Top {top_growth_rate_n} Countries with Highest Growth Rate in 2022:\n', )
top_growth_rate_countries

In [ ]:
largest_by_continent = df2.loc[df2.groupby('Continent')['2022 Population'].idxmax(), ['Continent', 'Country', '2022 Population']]
print('Largest Populated Country in Each Continent:')
largest_by_continent

In [ ]:
top5_by_continent = df2.groupby('Continent').apply(lambda x: x.nlargest(5, '2022 Population')).reset_index(drop=True)
print("Top 5 Largest Populated Countries in Each Continent:\n",)
top5_by_continent[['Continent', 'Country', '2022 Population']]

The idxmin method in pandas is used to find the index of the first occurrence of the minimum value in a Series. It returns the index label of the first occurrence where the minimum value is found.



In [ ]:

least_by_continent = df2.loc[df2.groupby('Continent')['2022 Population'].idxmin(), ['Continent', 'Country', '2022 Population']]
print("Least Populated Country in Each Continent:\n", )
least_by_continent

When you perform operations like grouping in pandas, it often results in a new DataFrame with a hierarchical index, which is a multi-level index based on the grouping columns. The reset_index method is then used to remove this hierarchical index and revert to the default integer index.

In [ ]:
least5_by_continent = df2.groupby('Continent').apply(lambda x: x.nsmallest(5, '2022 Population')).reset_index(drop=True)
print("Least Populated Countries in Each Continent:\n", )
least5_by_continent[['Continent', 'Country', '2022 Population']]